# Generated by Django 4.1.9 on 2023-12-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_pathmanager_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pathmanager",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
