# Generated by Django 4.1.9 on 2023-12-28 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0004_alter_pathmanager_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolderManager",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("FolderName", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("path", models.CharField(max_length=400)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
